#!/bin/bash

# USERS MUST CHANGE THESE !!!!!!
SWIFT_DIR='~/SWIFT_SyMBAp_pub'
SWIFT_DIR="${SWIFT_DIR/#\~/$HOME}"
FORTRAN=gfortran
FFLAGS='-O -march=native -fopenmp -c'
PRECOMP=/usr/bin/cpp
CPPFLAGS='-march=native -fopenmp -D_OPEN_POSITION -D_RECUR_SUB'

# To Profile the code:
if [ `ls *.F | wc -l` != 0 ]
then
    echo Doing precompiler
    for file in *.F
    do
        echo $file
        file2="${file%%.*}"
        echo $PRECOMP $CPPFLAGS "$file2".F "$file2"_CPP.f
        $PRECOMP $CPPFLAGS "$file2".F "$file2"_CPP.f
    done
else
    echo No need to precompile
fi

i=1
echo Doing Fortran
for file in *.f
do
    echo [$i] $file
    file2="${file%%.*}"
    $FORTRAN $FFLAGS $file2.f
    ar vr $SWIFT_DIR/libswift.a $file2.o
    ((i++))
done

rm -f *.o
rm -f *CPP.f
echo Done directory $PWD
