#!/bin/bash
cd src

mkdir -p build && rm -f build/*

echo DIRECTORY: mod
cd mod
rm -f @make_mod
ln -s ../@make_mod .
bash @make_mod

echo DIRECTORY: anal
cd ../anal
rm -f @make
ln -s ../@make .
bash @make

echo DIRECTORY: coord
cd ../coord
rm -f @make
ln -s ../@make .
bash @make

echo DIRECTORY: discard
cd ../discard
rm -f @make
ln -s ../@make .
bash @make

echo DIRECTORY: io
cd ../io
rm -f @make
ln -s ../@make .
bash @make

cd ../mvs

echo DIRECTORY: mvs/drift
cd drift
rm -f @make
ln -s ../../@make .
bash @make

echo DIRECTORY: mvs/getacch
cd ../getacch
rm -f @make
ln -s ../../@make .
bash @make

echo DIRECTORY: mvs/kickvh
cd ../kickvh
rm -f @make
ln -s ../../@make .
bash @make

cd ..

echo DIRECTORY: orbel
cd ../orbel
rm -f @make
ln -s ../@make .
bash @make

echo DIRECTORY: rmvs
cd ../rmvs
rm -f @make
ln -s ../@make .
bash @make

echo DIRECTORY: obl
cd ../obl
rm -f @make
ln -s ../@make .
bash @make

echo DIRECTORY: util
cd ../util
rm -f @make
ln -s ../@make .
bash @make

echo DIRECTORY: helio
cd ../helio
rm -f @make
ln -s ../@make .
bash @make

echo DIRECTORY: symba5p
cd ../symba5p
rm -f @make
ln -s ../@make .
bash @make

cd ../main
rm -f @make_main
ln -s ../@make_main .
bash @make_main

echo DONE
