#!/bin/bash

# USERS MUST CHANGE THESE !!!!!!
SWIFT_DIR="${HOME}/SWIFT_SyMBAp_pub"
FORTRAN=gfortran
FFLAGS='-O2 -ftree-vectorize -march=native -fopenmp -c'

i=1
echo Doing Fortran
for file in *.f
do
    echo [$i] $file
    file2="${file%%.*}"
    $FORTRAN $FFLAGS $file2.f
    ar vr $SWIFT_DIR/libswift.a $file2.o
    ((i++))
done

rm -f *.o
echo Done directory $PWD
