#!/bin/bash

# USERS MUST CHANGE THESE !!!!!!
SWIFT_DIR=$(pwd)
FORTRAN=gfortran-13
FFLAGS='-O -march=native -fopenmp'

i=1
for file in *.f
do
    echo [$i] $file
    file2="${file%%.*}"
    $FORTRAN $FFLAGS -o $file2 $file -L$SWIFT_DIR -lswift
    ((i++))
done
