#!/bin/bash

# USERS MUST CHANGE THESE !!!!!!
SWIFT_DIR="${HOME}/SWIFT_SyMBAp_pub"
FORTRAN=gfortran-13
FFLAGS='-O -march=native'

i=1
for file in *.f
do
    echo [$i] $file
    file2="${file%%.*}"
    if [ $file == swift_symba5p.f ]
    then
        $FORTRAN $FFLAGS -fopenmp -o $file2 $file -L$SWIFT_DIR -lswift
    else
        $FORTRAN $FFLAGS -o $file2 $file -L$SWIFT_DIR -lswift
    fi
    ((i++))
done
