#!/bin/bash

# USERS MUST CHANGE THESE !!!!!!
SWIFT_DIR="${HOME}/SWIFT_SyMBAp_pub"
FORTRAN=gfortran-13
FFLAGS='-O3 -ftree-vectorize -march=native -fopenmp -Wall -c'

i=1
for file in *.f90
do
    echo [$i] $file
    file2="${file%%.*}"
    $FORTRAN $FFLAGS $file2.f90 -I$SWIFT_DIR/src/build
    ar r $SWIFT_DIR/src/build/libswift.a $file2.o
    ((i++))
done

rm -f *.o
echo Done directory $PWD
