#!/bin/bash
mkdir -p build
cd build && rm -f *

echo DIRECTORY: mod
cd mod
rm @make_mod
ln -s ../@make_mod .
bash @make_mod

echo DIRECTORY: anal
cd ../anal
rm @make
ln -s ../@make .
bash @make

echo DIRECTORY: coord
cd ../coord
rm @make
ln -s ../@make .
bash @make

echo DIRECTORY: discard
cd ../discard
rm @make
ln -s ../@make .
bash @make

echo DIRECTORY: io
cd ../io
rm @make
ln -s ../@make .
bash @make

cd ../mvs

echo DIRECTORY: mvs/drift
cd drift
rm @make
ln -s ../../@make .
bash @make

echo DIRECTORY: mvs/getacch
cd ../getacch
rm @make
ln -s ../../@make .
bash @make

echo DIRECTORY: mvs/kickvh
cd ../kickvh
rm @make
ln -s ../../@make .
bash @make

cd ..

echo DIRECTORY: orbel
cd ../orbel
rm @make
ln -s ../@make .
bash @make

echo DIRECTORY: rmvs
cd ../rmvs
rm @make
ln -s ../@make .
bash @make

echo DIRECTORY: obl
cd ../obl
rm @make
ln -s ../@make .
bash @make

echo DIRECTORY: util
cd ../util
rm @make
ln -s ../@make .
bash @make

echo DIRECTORY: helio
cd ../helio
rm @make
ln -s ../@make .
bash @make

echo DIRECTORY: symba5p
cd ../symba5p
rm @make
ln -s ../@make .
bash @make

cd ..
ar ts libswift.a
ranlib libswift.a

echo DONE
