#!/bin/bash

# USERS MUST CHANGE THESE !!!!!!
SWIFT_DIR="${HOME}/SWIFT_SyMBAp_pub/src"
FORTRAN=gfortran-13
FFLAGS='-O2 -ftree-vectorize -march=native -fopenmp -Wall'

i=1
for file in *.f90
do
    echo [$i] $file
    file2="${file%%.*}"
    $FORTRAN $FFLAGS -o ../../$file2 $file -L$SWIFT_DIR/build -lswift -I$SWIFT_DIR/build
    ((i++))
done
