c*************************************************************************
c                        SYMBA5P.INC
c*************************************************************************
C Include file for the SyMBAp subroutines
c
c Remarks:  modified from symba5.inc
c Date:    7/23/21

c..    Maximum no. of pairs in a group
       integer GRPMAX
       parameter (GRPMAX = 500)
       
c..    Maximum no. of group
       integer GRPNMAX
       parameter (GRPNMAX = NENMAX)
       
c..    Note your stack size!
